import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :timberee, TimbereeWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :timberee, TimbereeWeb.Endpoint,
  url: [host: "timberee.local"],
  check_origin: ["http://timberee.local"],
  adapter: Bandit.PhoenixAdapter,
  render_errors: [
    formats: [html: TimbereeWeb.ErrorHTML, json: TimbereeWeb.ErrorJSON],
    layout: false
  ],
  pubsub_server: Timberee.PubSub,
  live_view: [signing_salt: "Eqp4dUEa"]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
